version: '3.8'

services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db
      MYSQL_USER: shidalgo
      MYSQL_PASSWORD: 12345
    restart: unless-stopped
    ports:
      - 3310:3306
    networks:
      - net-app
    volumes:
      - vol-app:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 10s
      retries: 3
      start_interval: 5s

  mysql-client:
    image: phpmyadmin
    container_name: mysql-client
    environment:
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - net-app
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 10s
      timeout: 10s
      retries: 3
      start_interval: 5s
    depends_on:
      mysql-server:
        condition: service_healthy

networks:
  net-app:
    driver: bridge
    name: net-app

volumes:
  vol-app:
    name: vol-app
