version: '3.8'

services:
  arq04-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/arquitectura5
    container_name: arq04-app
    restart: unless-stopped
    ports:
      - 3000:3000
