### Create user
POST http://localhost:3000/user
content-type: application/json

{
    "id": "169753fa-70b6-4e8e-925d-4fdc0f8e21ee",
    "fullname": "John Doe",
    "email": "person1@email.com",
    "image": "foto.jpg",
    "password": "Mundo12345",
    "roles": [{"id": "287e84a5-698d-4f6c-b5bf-4d2c0e4daa52"}, {"id": "cfd51374-d308-46ed-b656-d2257337c69a"}],
    "address": {
        "street": "Rua 1",
        "number": 123,
        "city": "Bogotá",
        "country": "Colombia"
    }
}

### List users
GET http://localhost:3000/user

### Get user by id
GET http://localhost:3000/user/169753fa-70b6-4e8e-925d-4fdc0f8e21ee

### Update user
PUT http://localhost:3000/user/169753fa-70b6-4e8e-925d-4fdc0f8e21ee
content-type: application/json

{
    "fullname": "John Doe2",
    "email": "john.doe2@email.domain.com"
}

### Update user
DELETE http://localhost:3000/user/169753fa-70b6-4e8e-925d-4fdc0f8e21ee

